SELECT * REPLACE (
    CAST(AESTDTC AS TIMESTAMP) as AESTDTC,
    CAST(NULLIF(AEENDTC, '') AS TIMESTAMP) as AEENDTC
),
DATEDIFF('day', CAST(AESTDTC AS TIMESTAMP), CAST(NULLIF(AEENDTC, '') AS TIMESTAMP)) as ae_duration_days
FROM {{source('raw', 'ae')}}