SELECT * REPLACE (
    CAST(NULLIF(RFSTDTC, '') AS TIMESTAMP) as RFSTDTC,
    CAST(NULLIF(RFENDTC, '') AS TIMESTAMP) as RFENDTC,
    CAST(DMDTC AS TIMESTAMP) as DMDTC,
    CAST(BRTHDTC AS DATE) as BRTHDTC,
    CAST(DSSTDTC AS DATE) as DSSTDTC,
    NULLIF(ARMCD, '') as ARMCD,
    NULLIF(ARM, '') as ARM
        )
FROM {{source('raw', 'dm')}}
