SELECT a.STUDYID, a.USUBJID, a.AESEQ, a.AETERM, a.AEDECOD, a.AESEV, a.AESER, a.AEREL, a.AEACN, a.AEOUT, 
a.AESTDTC, a.AEENDTC, a.ae_duration_days, 
d.ARMCD, d.ARM, d.AGE, d.SEX, 
CASE WHEN AESTDTC >= RFSTDTC THEN 'Y' ELSE 'N' END as TRTEMFL, 
CASE WHEN AESER = 'Y' AND AEREL IN ('RELATED', 'POSSIBLY RELATED') 
     THEN 'SERIOUS AND RELATED' 
     ELSE NULL 
END as CQ01NAM
FROM {{ref('stg_ae')}} a LEFT JOIN {{ref('stg_dm')}} d
ON a.USUBJID = d.USUBJID
