name: 'clinical_trial_analytics'
version: '1.0.0'

profile: 'clinical_trial_analytics'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  clinical_trial_analytics:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts
